services:
  backend:
    build:
      context: ./server
    container_name: olive-art-backend-container
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:3001/api
    container_name: olive-art-frontend-container
    ports:
      - "8081:80"
    depends_on:
      - backend